# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenGL Tutorial Chp.1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'glfw'

  # Pods for OpenGL Tutorial Chp.1

end
